/**
 * Build one self-contained executable per platform into out/.
 *   bun run build                 linux-x64 and windows-x64
 *   bun run build --target linux  one target
 * Steps: vite build -> embed apps/web/dist as base64 into embedded-web.ts -> bun build --compile -> restore stub.
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const repo = path.resolve(import.meta.dir, "..");
const dist = path.join(repo, "apps", "web", "dist");
const embedFile = path.join(repo, "apps", "server", "src", "http", "embedded-web.ts");
const entry = path.join(repo, "apps", "server", "src", "main.ts");
const outDir = path.join(repo, "out");

const TARGETS = {
  linux: { bunTarget: "bun-linux-x64", out: "couch-launcher-linux-x64", extra: [] as string[] },
  windows: {
    bunTarget: "bun-windows-x64",
    out: "couch-launcher-windows-x64.exe",
    // Hidden console: the service runs at sign-in without a window. `doctor` therefore writes its
    // report to a file as well as stdout (see DECISIONS D-014).
    extra: ["--windows-hide-console"],
  },
} as const;
type TargetName = keyof typeof TARGETS;

function sh(cmd: string[], cwd = repo) {
  console.log(`$ ${cmd.join(" ")}`);
  const r = Bun.spawnSync(cmd, { cwd, stdout: "inherit", stderr: "inherit" });
  if (r.exitCode !== 0) throw new Error(`failed: ${cmd.join(" ")}`);
}

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((n) => {
    const p = path.join(dir, n);
    return statSync(p).isDirectory() ? walk(p) : [p];
  });
}

const argIdx = process.argv.indexOf("--target");
const only = argIdx > 0 ? (process.argv[argIdx + 1] as TargetName | undefined) : undefined;
if (only && !(only in TARGETS)) throw new Error(`unknown target ${only}`);
const targets = (only ? [only] : Object.keys(TARGETS)) as TargetName[];

sh(["bun", "run", "build:web"]);
const stub = readFileSync(embedFile, "utf8");
const assets: Record<string, string> = {};
for (const f of walk(dist)) {
  const rel = `/${path.relative(dist, f).split(path.sep).join("/")}`;
  assets[rel] = readFileSync(f).toString("base64");
}
console.log(`embedding ${Object.keys(assets).length} web files`);
writeFileSync(
  embedFile,
  `// GENERATED by scripts/build.ts during compile. Do not commit.\nexport const EMBEDDED_WEB: Record<string, string> = ${JSON.stringify(assets)};\n`,
);
try {
  for (const t of targets) {
    const spec = TARGETS[t];
    sh([
      "bun",
      "build",
      "--compile",
      "--minify",
      "--sourcemap=none",
      `--target=${spec.bunTarget}`,
      ...spec.extra,
      entry,
      "--outfile",
      path.join(outDir, spec.out),
    ]);
    console.log(
      `built out/${spec.out} (${(statSync(path.join(outDir, spec.out)).size / 1e6).toFixed(1)} MB)`,
    );
  }
} finally {
  writeFileSync(embedFile, stub);
}
